[project]
name = "qmk-firmware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "argcomplete>=3.6.2",
    "colorama>=0.4.6",
    "hjson>=3.1.0",
    "pygments>=2.19.2",
    "qmk>=1.1.8",
]
